### ISSUE TITLE
RuntimeError: Running command git clone

### ISSUE THREAD

**Issue by anki-code** [niess/python-appimage#11]
Hello! Thank you for your work here!

To install from git like:
```
pip install git+https://github.com/xonsh/xonsh
```
I've added git url to `appliactions/xonsh/requirements.txt`:
```
git+https://github.com/xonsh/xonsh
prompt_toolkit
Pygments
```
And I've got an error:
```
$ python -m python_appimage build app applications/xonsh
[2020-04-21 09:09:23,913] EXTRACT  python3.8.2-cp38-cp38-manylinux1_x86_64.AppImage
[2020-04-21 09:09:40,715] BUNDLE   xonsh.desktop
[2020-04-21 09:09:40,716] BUNDLE   xonsh.appdata.xml
[2020-04-21 09:09:42,202] BUNDLE   git+https://github.com/xonsh/xonsh
Traceback (most recent call last):
  File "/home/pc/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pc/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pc/xxh/python-appimage/python_appimage/__main__.py", line 92, in <module>
    main()
  File "/home/pc/xxh/python-appimage/python_appimage/__main__.py", line 88, in main
    command.execute(*command._unpack_args(args))
  File "/home/pc/xxh/python-appimage/python_appimage/commands/build/app.py", line 224, in execute
    exclude=deprecation)
  File "/home/pc/xxh/python-appimage/python_appimage/utils/system.py", line 42, in system
    raise RuntimeError(err)
RuntimeError:   Running command git clone -q https://github.com/xonsh/xonsh /tmp/pip-req-build-t16gwmrn
```

If I run just `git clone -q https://github.com/xonsh/xonsh /tmp/pip-req-build-t16gwmrn` it works.

What I'm doing wrong?

Thanks!

**Comment by niess** [comment]
@anki-code You are doing nothing wrong. Most likely this command writes to stderr and I am wrongly flagging this as an error. I'll have to parse stderr and check its content.

Meanwhile you can post install, e.g. by extracting the AppImage and running `squashfs/usr/bin/pip install git+https://...`. And then rebuild it with `appimagetool`.

**Comment by niess** [comment]
@anki-code It has been patched. It should work now. Doesn't it?

**Comment by anki-code** [comment]
It works! Thanks! 🎉  👍

**Comment by niess** [comment]
Great :)
