### ISSUE TITLE
The unwanted crashing in case of warning: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager.

### ISSUE THREAD

**Issue by anki-code** [niess/python-appimage#44]
Hi!

The [xxh project](https://github.com/xxh/xxh) built system based on docker containers [was crashed with error](https://github.com/xxh/xxh/runs/4577008288?check_suite_focus=true#step:5:456):

```
Step 9/10 : RUN python -m python_appimage build app /xxh/appimage
 ---> Running in 83823cdd8082
[2021-12-20 00:19:42,633] EXTRACT  python3.9.9-cp39-cp39-manylinux1_x86_64.AppImage
[2021-12-20 00:19:43,561] BUNDLE   xxh.desktop
[2021-12-20 00:19:43,562] BUNDLE   xxh.appdata.xml
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/python_appimage/__main__.py", line 113, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/python_appimage/__main__.py", line 109, in main
    command.execute(*command._unpack_args(args))
  File "/usr/local/lib/python3.8/site-packages/python_appimage/commands/build/app.py", line 245, in execute
    system(('./AppDir/AppRun', '-m', 'pip', 'install', '-U', in_tree_build,
  File "/usr/local/lib/python3.8/site-packages/python_appimage/utils/system.py", line 42, in system
    raise RuntimeError(err)
RuntimeError: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

```

Please add ignoring of this pip warning.

Thanks!

**Comment by niess** [comment]
Hey @anki-code,

the warning message might have changed. I updated `python-appimage` in order to accept more generic pip warnings. Does it solve your issue?

**Comment by anki-code** [comment]
Yes! It works now! Many thanks @niess!
