### ISSUE TITLE
AttributeError: module 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by Fakem1ner** [niess/python-appimage#53]
```
$ python-appimage build app main.py
Traceback (most recent call last):
  File "/home/fakeminer/.local/bin/python-appimage", line 8, in <module>
    sys.exit(main())
  File "/home/fakeminer/.local/lib/python3.10/site-packages/python_appimage/__main__.py", line 100, in main
    command = import_module(module, package=__package__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/fakeminer/.local/lib/python3.10/site-packages/python_appimage/commands/build/app.py", line 10, in <module>
    from ...appimage import build_appimage
  File "/home/fakeminer/.local/lib/python3.10/site-packages/python_appimage/appimage/__init__.py", line 1, in <module>
    from .build import build_appimage
  File "/home/fakeminer/.local/lib/python3.10/site-packages/python_appimage/appimage/build.py", line 7, in <module>
    from ..utils.compat import decode
  File "/home/fakeminer/.local/lib/python3.10/site-packages/python_appimage/utils/compat.py", line 27, in <module>
    find_spec = importlib.util.find_spec
AttributeError: module 'importlib' has no attribute 'util'
```

Operating system Linux Ubuntu 22.04

**Comment by niess** [comment]
Hello @Fakem1ner . Sorry about this. It should be solved now with [PR 51](https://github.com/niess/python-appimage/pull/51).
