### ISSUE TITLE
xonsh appimage stop after first command

### ISSUE THREAD

**Issue by anki-code** [niess/python-appimage#8]
Hi! Thank you for the `python-appimage`! It's straight forward!

I tested xonsh appimage inside [xxh](https://github.com/xxh/xxh) and it worked. Now I try to run xonsh appimage as is and I've got unexpected behavior. I tried [linuxdeploy-plugin-python](https://github.com/niess/linuxdeploy-plugin-python/) xonsh appimage version and got the same.

1. xonsh stops after any command and freeze process:
```
bash
mkdir -p /tmp/test && cd /tmp/test
git clone https://github.com/niess/python-appimage && cd python-appimage
python -m python_appimage build app applications/xonsh
./xonsh-x86_64.AppImage
xonsh> echo 123
[1]+  Stopped                 ./xonsh-x86_64.AppImage

Failback to /bin/sh
Traceback (most recent call last):
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 24189, in main
    return main_xonsh(args)
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 24218, in main_xonsh
    shell.shell.cmdloop()
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/xonsh/ptk2/shell.py", line 197, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/xonsh/ptk2/shell.py", line 166, in singleline
    line = self.prompter.prompt(**prompt_args)

  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 994, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 811, in run
    return loop.run_until_complete(
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 778, in run_async
    return await _run_async2()
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 760, in _run_async2
    result = await _run_async()
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 682, in _run_async
    with self.input.raw_mode():
  File "/tmp/.mount_xonsh-DFQ6bT/usr/python/lib/python3.8/site-packages/prompt_toolkit/input/vt100.py", line 259, in __enter__
    termios.tcsetattr(self.fileno, termios.TCSANOW, newattr)
termios.error: (5, 'Input/output error')

```
2. And the process not really closed:
```
$ ps -ax | grep xonsh
  862 pts/0    T      0:00 /bin/bash /tmp/.mount_xonsh-10lrWf/AppRun
  866 ?        Ssl    0:00 ./xonsh-x86_64.AppImage
  869 pts/0    T      0:00 /bin/bash /tmp/.mount_xonsh-10lrWf/usr/bin/python3.8 -u -c from xonsh.main import main; main()
  882 pts/0    S      0:00 /home/ubuntu/python-appimage/xonsh-x86_64.AppImage -u -c from xonsh.main import main; main()
```
3. And when I try to type any commands in the `bash` terminal where I run `./xonsh-x86_64.AppImage` I've got endless errors:
```
Traceback (most recent call last):
  File "/tmp/.mount_xonsh-10lrWf/opt/python3.8/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 24206, in func_sig_ttin_ttou
    def func_sig_ttin_ttou(n, f):
BlockingIOError: [Errno 11] Resource temporarily unavailable
Exception ignored when trying to write to the signal wakeup fd:
```
4. After `kill` xonsh process the bash returns to ordinary work.

If you can help it will be great. Thanks!

**Comment by anki-code** [comment]
It looks like xonsh regress. Sorry.

**Comment by niess** [comment]
@anki-code I had similar issues at some point. I don't where this comes from. Right now its working for me. Is it related to Xonsh itself?

**Comment by anki-code** [comment]
I think it's xonsh regress. I described the details in https://github.com/xonsh/xonsh/issues/3525

**Comment by anki-code** [comment]
When I run `xonsh.AppImage` in bash I have this issue. When I run it from xonsh it works. I think the problem in how xonsh read and set environment.
